// See https://aka.ms/new-console-template for more information
using Academy_OOP;
Academy academy1 = new Academy("Makeen", "Iran, Tehran, Resalat", "ASP.NET - React.JS - UI/UX");
MainBootCamp mbc1 = new MainBootCamp(0, "ASP.NET", "C#, Database, Project");
MainBootCamp mbc2 = new MainBootCamp(1, "React.JS", "JavaScript, CSS, Html");
MainBootCamp mbc3 = new MainBootCamp(2, "UI/UX", "Design, Photoshop, Illastrator");
Room rm1 = new Room("R001", "Video Prejctor", 10);
Room rm2 = new Room("R002", "Smart board", 8);
Room rm3 = new Room("R003", "PC", 15);
BootCamp bc1 = new BootCamp(0, new DateTime(2025, 9, 15));
BootCamp bc2 = new BootCamp(1, new DateTime(2025, 9, 16));
BootCamp bc3 = new BootCamp(2, new DateTime(2025, 9, 17));
Employee ep1 = new Employee("Amin", "Rashidinezhad", "0012142222");
Employee ep2 = new Employee("Reza", "Amini", "0012882222");
Employee ep3 = new Employee("Sadegh", "Nazari", "0222142222");
Student st1 = new Student("Ehsan", "Arefzadeh", "0024264784");
Student st2 = new Student("Ali", "Zamani", "0023245687");
Student st3 = new Student("Hossein", "Afzali", "0012141534");
Student st4 = new Student("Alireza", "Arefzadeh", "0024264785");
academy1.AddMainBootCamp(mbc1);
academy1.AddMainBootCamp(mbc2);
academy1.AddMainBootCamp(mbc3);
academy1.AddBootCamp(bc1, mbc1);
academy1.AddBootCamp(bc2, mbc2);
academy1.AddBootCamp(bc3, mbc3);
academy1.AddEmployee(ep1, bc1);
academy1.AddEmployee(ep2, bc2);
academy1.AddEmployee(ep3, bc3);
academy1.AddRoom(rm1, bc1);
academy1.AddRoom(rm2, bc2);
academy1.AddRoom(rm3, bc3);
academy1.AddStudent(st1, bc1);
academy1.AddStudent(st2, bc2);
academy1.AddStudent(st3, bc3);
academy1.AddStudent(st4, bc1);
//------------------------------------------------------------Created By Ehsan Arefzadeh (Git Test)
Console.WriteLine("Academy Information--------------------------");
academy1.GetInfo();
Console.WriteLine("Main Boot Camps-------------------------");
academy1.GetMainBootCamp();
Console.WriteLine("Available Boot Camps-------------------------");
academy1.GetBootCamp(mbc1);
academy1.GetStudent(mbc1);
Console.WriteLine();
academy1.GetBootCamp(mbc2);
academy1.GetStudent(mbc2);
Console.WriteLine();
academy1.GetBootCamp(mbc3);
academy1.GetStudent(mbc3);
